runtime! debian.vim
syntax on
colorscheme desert
set noautoindent
set nocindent
set nocompatible
set nocursorline
set nomodeline
set nottyfast
set nosmartindent
set backspace=indent,eol,start
set indentexpr=
set mouse=r
set ruler
set scroll=25
set ttymouse=sgr
