#!/bin/bash
#
# cmpcode - compare code in $HOME/minimy and $HOME/minimy-mike99mac 
#
# NOTE: it is hard coded for Minimy - needs to be updated for OVOS
#
copyCmds=""                                # copy commands 
diffCmds=""                                # copy commands 
gitCode="$HOME/minimy-mike99mac"           # git code
srcCode="$HOME/minimy"                     # running code
omit1="framework/services/tts/local/mimic3/*"   # files that never change
omit2="framework/services/stt/local/CoquiSTT/*" # more

cd /home/pi/minimy
# sourceFiles=`find skills/ bus/ framework/ display/ -name "*.py" ! -path "$omit1" ! -path "$omit2"`
sourceFiles=`ls bus/*py framework/*py framework/*/*py framework/*/*/*py framework/*/*/*/*py skills/*py skills/*/*py skills/*/*/*py | xargs`
for nextFile in $sourceFiles; do
  echo "comparing $nextFile ..."
  diff $srcCode/$nextFile $gitCode/$nextFile >/dev/null
  if [ $? != 0 ]; then                     # file has changed
    if [ ${#copyCmds} = 0 ]; then          # first copy command
      copyCmds="cp $srcCode/$nextFile $gitCode/$nextFile"
      diffCmds="diff $srcCode/$nextFile $gitCode/$nextFile"
    else
      copyCmds="$copyCmds \ncp $srcCode/$nextFile $gitCode/$nextFile"
      diffCmds="$diffCmds \ndiff $srcCode/$nextFile $gitCode/$nextFile"
    fi
  fi
done

if [ ${#copyCmds} = 0 ]; then              # nothing changed
  echo "No code changes found in $srcCode"
else                                       # at least one change
  copycode="/usr/local/sbin/copycode"
  tmpFile=`mktemp`
  echo "#!/bin/bash" > $tmpFile            # restart file
  echo -e "$copyCmds" >> $tmpFile          # add copy commands with newlines
  sudo mv $tmpFile $copycode               # script to copy modified files
  sudo chown $USER.$USER $copycode     
  sudo chmod 755 $copycode      
  echo "Copy commands in: $copycode"
  echo
  cat $copycode
fi 
echo
echo "diff commands"
echo -e $diffCmds

