#!/bin/bash
#
# gitc - wrapper around "git commit -a -m" 
#
if [ $# = 0 ]; then                        # no args passed
  echo "Usage: gitc <Description of changes>"
  exit 1
fi
git commit -a -m "$@"
