#!/bin/bash
#
# grm - short command to search through Minimy python files 
#
cd $HOME/minimy
grep --color -n "$@" *py bus/*py framework/*py framework/*/*py framework/*/*/*py framework/*/*/*/*/*py framework/*/*/*/*py skills/*py skills/*/*py skills/*/*/*py 2>/dev/null | sed "s:^:$HOME/minimy/:g"
