#!/bin/bash
#
# grm - short command to search through Minimy python files 
#
cd $HOME/minimy
fw="$HOME/minimy/framework"
frameworkFiles="$fw/*py $fw/*/*py $fw/*/*/*py $fw/*/*/*/*py $fw/*/*/*/*/*py $fw/*/*/*/*/*/*py $fw/*/*/*/*/*/*/*py"
mn="$HOME/minimy"
srcFiles="$mn/*py $mn/bus/*py $mn/skills/*py $mn/skills/*/*py $mn/skills/*/*/*py"
grep -n --color "$@" $frameworkFiles $srcFiles 2>/dev/null 
