#!/bin/bash
#
# grn - GRep Neon/OVOS code for the supplied pattern
#
if [ $# = 0 ]; then                        # no args passed
  echo "ERROR: no search pattern passed in"
  echo "Usage: gro SEARCH_PATTERN"
  exit 1
fi

baseDir="$HOME/venv/lib/python3.*/site-packages"
if [ ! -d $baseDir ]; then
  echo "ERROR: Directory $baseDir not found" 
  exit 1
fi

echo
echo "Searching Python files below $baseDir ..."
echo
cd $baseDir
grep -n "$@" */*.py ovos_*/*/*.py */*/*/*.py */*/*/*/*.py */*/*/*/*/*.py */*/*/*/*/*/*.py | sed "s:^:$baseDir/:g"

