#!/bin/bash
#
# grn - GRep Neon/OVOS code for the supplied pattern
#
if [ $# = 0 ]; then                        # no args passed
  echo "ERROR: no search pattern passed in"
  echo "Usage: grn SEARCH_PATTERN"
  exit 1
fi

pyDir=`ls -d $HOME/venv/lib/python3.*`
if [ ! -d $pyDir ]; then
  echo "ERROR: Python directory not found in $HOME/venv/lib/python3.* Is this a Neon box?"
  exit 1
fi
baseDir="$pyDir/site-packages"
if [ ! -d $baseDir ]; then
  echo "ERROR: Directory $baseDir not found. Is this a Neon box?"
  exit 2
fi

echo
echo "Searching Python files below $baseDir ..."
echo
cd $baseDir
grep -n "$@" */*.py ovos_*/*/*.py */*/*/*.py */*/*/*/*.py */*/*/*/*/*.py */*/*/*/*/*/*.py | sed "s:^:$baseDir/:g"

