#!/bin/bash
#
# gro - GRep Ovos code for the supplied pattern
#
if [ $# = 0 ]; then                        # no args passed
  echo "ERROR: no search pattern passed in"
  echo "Usage: gro SEARCH_PATTERN"
  exit 1
fi

pythonVer=`python3 -V | awk '{print $2}' | awk -F. '{print $1 "." $2}'`
baseDir="$HOME/ovos_venv/lib/python${pythonVer}/site-packages"
if [ ! -d $baseDir ]; then
  echo "ERROR: Directory $baseDir not found - is OVOS installed?"
  exit 1
fi

echo
echo "Searching Python files below $baseDir ..."
echo
cd $baseDir
grep --color -n "$@" ovos_*/*.py ovos_*/*/*.py ovos_*/*/*/*.py skill_ovos_*/*.py skill_ovos_*/*/*.py | sed "s:^:$baseDir/:g"

