#!/bin/bash
#
# installovos - create a venv then install OVOS into it
#
#+--------------------------------------------------------------------------+
function usage
# Parse arguments
# Args: All arguments passed into script
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  echo
  echo "Name:  installovos - install OVOS in a virtual environment"
  echo "Usage: installovos [OPTIONS]"
  echo ""
  echo "OPTIONS:"
  echo "  -h|--help         Give help (this screen)"
  echo "  -v|--verbose      Increase verbosity"
  echo "  -x|--debug        Print commands and arguments as they are executed"
  echo "  -y|--yes          Do not prompt to remove old venv"
  exit 51
 }                                         # usage()

#+--------------------------------------------------------------------------+
function parseArgs
# Parse arguments
# Args: All arguments passed in 
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  while [ -n "$1" ]                        # loop through args passed in
  do
    case "$1" in
      -h|--help)
        usage
        ;;
      -v|--verbose)
        verbose=2
        ;;
      -x|--debug)                          # turn trace on
         set -vx
         ;;
      -y|--yes)                            # do not prompt
         yes="yes"
         ;;
      *)
        echo "ERROR: Unrecognized argument: $1"
        usage
        ;;
    esac
    shift
  done
 }                                         # parseArgs()

#+--------------------------------------------------------------------------+
function runCmd
# run a command, report time spent and exit if it failes
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  cmd="$@"                                 # get all args
  echo "Running: $cmd ..." | tee -a $outFile # show the command and send to output file
  eval $cmd >> $outFile 2>&1               # run the command
  rc=$?
  if [ "$rc" != 0 ]; then                  # it failed
    echo "ERROR: $cmd returned $rc" | tee -a $outFile
    exit 1
  fi
 }                                         # runCmd()

#+--------------------------------------------------------------------------+
function installWithGit 
# install package with git clone
# Arg 1: the URL to install
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  local thePkg="$@"
  let curPkg=$curPkg+1
  echo
  echo "Installing package $curPkg of $pkgCnt: $thePkg..." | tee -a $outFile
  runCmd git clone https://github.com/OpenVoiceOS/$thePkg 
 }                                         # installWithGit()

#+--------------------------------------------------------------------------+
function installWithPip
# install package with "pip install git+URL"
# Arg 1: the URL to install
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  local thePkg="$@"
  let curPkg=$curPkg+1
  echo
  echo "Installing package $curPkg of $pkgCnt: $thePkg..." | tee -a $outFile
  runCmd pip install $thePkg 
 }                                         # installWithPip()

#+--------------------------------------------------------------------------+
function installWithGitPip 
# install package with "pip install git+URL"
# Arg 1: the URL to install
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  local thePkg="$@"
  let curPkg=$curPkg+1
  echo
  echo "Installing package $curPkg of $pkgCnt: $thePkg..." | tee -a $outFile
  runCmd pip install git+https://github.com/OpenVoiceOS/$thePkg 
 }                                         # installWithGitPip()

#+--------------------------------------------------------------------------+
function copyServiceFile
# Copy a systemd service file from ovos-tools to run as root or user then enable and start it
# Arg 1: service file name
# Arg 2: "root" or "user"
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  local serviceName="$1"
  local serviceType=$2    
  local serviceFQDN="$HOME/ovos-tools/$1.service"
  local systemdDir="$HOME/.config/system/user"

  if [ ! -f $serviceFQDN ]; then
    echo "ERROR: service file $serviceFQDN not found - is ovos-tools installed?"
    exit 2
  fi    
  if [ ! -d $systemdDir ]; then            # systemd directory does not exist
    local cmd="mkdir -p $HOME/.config/system/user"
    runCmd $cmd
  fi

  if [ "$serviceType" = root ]; then       # copy to systemd system directory
    runCmd sudo cp $serviceFQDN /etc/systemd/system
    runCmd sudo systemctl enable $serviceName 
    runCmd sudo systemctl start $serviceName 
  elif [ "$serviceType" = user ]; then     # copy to systemd user directory
    runCmd sudo cp $serviceFQDN $systemdDir
    runCmd systemctl --user enable $serviceName
    runCmd systemctl --user start $serviceName
  else                                     # not expected
    echo "INTERNAL ERROR: serviceType = $serviceType"
    exit 3
  fi
 }                                         # copyServiceFile()

#+--------------------------------------------------------------------------+
function installOVOS
# Do the work to install ovos-core into a venv 
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  local date=`date`
  echo "Running installovos on $date ..." | tee -a $outFile
  echo 
  if [ -d ~/.venvs ]; then                 #  directory exists
    if [ "$1" != "-y" ]; then 
      echo -n "~/.venvs directory exists - do you want to remove it and rebuild? (y/n) "
      read ans
      if [ "$ans" != y -a "$ans" != Y ]; then
        exit 4
      fi
    fi
    echo "removing ~/.venvs directory ..."
    /usr/bin/rm -fr $HOME/.venvs | tee -a $outFile
    if [ $? != 0 ]; then 
      echo "/usr/bin/rm -fr $HOME/.venvs returned $? trying again ..."
      /usr/bin/rm -fr $HOME/.venvs | tee -a $outFile
      if [ $? != 0 ]; then 
        echo "/usr/bin/rm -fr $HOME/.venvs failed again with $? ... punt! ..." | tee -a $outFile
        exit 5
      fi
    fi	    
  fi

  if [ ! -f $HOME/ovos-tools/ovos.git.packages  ]; then
    echo "ERROR: $HOME/ovos-tools/ovos.git.packages not found - is ovos-tools installed?" | tee -a $outFile
  fi
  
  echo | tee -a $outFile
  echo "Creating a virtual environment ..." | tee -a $outFile
  cd                                       # cd to home directory
  runCmd mkdir -p .venvs/ovos
  runCmd python3 -m venv ~/.venvs/ovos
  cd .venvs/ovos                        

  echo | tee -a $outFile
  echo "Activating virtual environment ..." | tee -a $outFile
  runCmd source ./bin/activate

  echo | tee -a $outFile
  echo "Cloning ovos-core ..." | tee -a $outFile
  runCmd git clone https://github.com/OpenVoiceOS/ovos-core
  
  echo | tee -a $outFile
  echo "Installing packages with apt-get ..." | tee -a $outFile
  runCmd sudo apt-get install -y build-essential python3-dev swig libssl-dev libfann-dev libpulse-dev libasound2-dev mpg123 portaudio19-dev python3-pyaudio liblapack-dev libopenblas-dev flac
  
  echo | tee -a $outFile
  echo "Installing wheel with pip install ..." | tee -a $outFile
  runCmd pip install wheel                 # wheel needs to be in place before other packages 

  echo | tee -a $outFile
  echo "Installing other non-ovos packages with pip install ..." | tee -a $outFile
  runCmd pip install silero tornado 

  echo | tee -a $outFile
  echo "Installing ovos-core ..." | tee -a $outFile
  runCmd "pip install ovos-core[mycroft]"

  # some packages are "git clone"d, some just use pip and others need pip+git
  local nextPkg
  echo "Installing ovos packages with git ..." | tee -a $outFile
  local gitPkgs=`cat $HOME/ovos-tools/ovos.git.packages | xargs`
  for nextPkg in $gitPkgs; do
    installWithGit $nextPkg
  done

  echo "Installing ovos packages with pip ..." | tee -a $outFile
  local pipPkgs=`cat $HOME/ovos-tools/ovos.pip.packages | xargs`
  for nextPkg in $pipPkgs; do
    installWithPip $nextPkg
  done

  echo "Installing ovos packages with install ..." | tee -a $outFile
  local pipPkgs=`cat $HOME/ovos-tools/ovos.pip+git.packages | xargs`
  for nextPkg in $pipPkgs; do
    installWithGitPip $nextPkg
  done

  echo | tee -a $outFile
  echo "Copying ovos_PHAL_admin file ..." | tee -a $outFile
  runCmd cp ~/ovos-tools/ovos_PHAL_admin ~/.venvs/ovos/bin

  echo | tee -a $outFile
  echo "Copying .service files and setting to run at boot time .." | tee -a $outFile
  copyServiceFile ovos-phal-admin root     # the one service that runs as root
  for nextService in ovos-audio ovos-core ovos-listener ovos-media ovos-messagebus ovos-phal; do
    copyServiceFile $nextService user
  done
 }                                         # installOVOS()

# main()
curPkg=0                                   # current package being installed
pkgCnt=0                                   # of packages
verbose=1                                  # verbosity
yes="no"

parseArgs $@                               # parse arguments
timeStamp=`date +"%y-%m-%d-%H:%M:%S"`      # YY-MM-DD-HH:MM:SS
outFile="$HOME/$timeStamp-installovos.out" # output file
pkgCnt=`wc -l $HOME/ovos-tools/*.packages | tail -1 | awk '{print $1}'`

echo "installovos run at $timeStamp" > $outFile # start new output file
installOVOS $@                             # do the work
let min=$SECONDS/60                        # show time spent installing
let sec=$SECONDS%60
if [ $sec -lt 10 ]; then                   # add a leading 0
  sec="0$sec"
fi
echo | tee -a $outFile
echo "Successfully installed OVOS in $min:$sec" | tee -a $outFile

