#!/bin/bash
#
# install1 - configure a new Linux for a Minimy or OVOS installation
#
#+--------------------------------------------------------------------------+
function usage()
# Give help to the user
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  echo "install1 - configure Linux for Minimy, Neon or OVOS"
  echo "Usage: install1 [OPTIONS]" 
  echo ""
  echo "OPTIONS:"
  echo "  -h|--help         Give help (this screen)"
  echo "  -m|--minimy       Configure for Minimy (default)"
  echo "  -n|--neon         Configure for Neon"
  echo "  -o|--ovos         Configure for OVOS"
  echo "  -v|--verbose      Increase verbosity"
  echo "  -x|--debug        Print commands and arguments as they are executed"
  echo ""
  exit 51
 }                                         # usage()

#+--------------------------------------------------------------------------+
function parseArgs()
# Parse arguments
# Args: All arguments passed into script
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  while [ -n "$1" ]                        # loop through args passed in
  do
    case "$1" in
      -c|--cardnum)
        if [ $# = 0 ]; then                # CARD not passed in
          echo "ERROR! CARD not passed in after $1"
          usage                            # give help
        fi
        shift                              # get to next arg
        cardToUse=$1
        ;;
      -h|--help)
        usage
        ;;
      -m|--minimy)
        flavor="minimy" 
        ;;
      -n|--neon)
        flavor="neon" 
        ;;
      -o|--ovos)
        flavor="ovos" 
        ;;
      -v|--verbose)
        verbose=2
        flags="-v"
        ;;
      -x|--debug)                          # turn trace on
         set -vx
         ;;
      *)
        echo "ERROR: Too many arguments: $1"
        usage
        ;;
    esac
    shift
  done
 }                                         # parseArgs()

#+--------------------------------------------------------------------------+
function checkOvosTools
# Check that ovos-tools is installed in $HOME 
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  baseDir="$HOME/ovos-tools"
  if [ ! -d $baseDir ]; then
    echo "ERROR: Did not find ovos-tools in $baseDir"
    exit 1
  fi
 }                                         # checkOvosTools()

#+--------------------------------------------------------------------------+
function runCmd
# run a command, report time spent and exit if it fails
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  cmd="$@"                                 # all args

  echo " " 
  echo "Running: $cmd" 
  eval $cmd 2>&1 
  rc=$?
  if [ "$rc" != 0 ]; then                  # it failed
    echo "ERROR: $cmd returned $rc" 
    exit 1
  else
    echo "Command was successful!" 
  fi
 }                                         # runCmd()

#+--------------------------------------------------------------------------+
function installCoreqs
# Do the work to install and configure everything to run Mycroft driven by ovos-core
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  distro=`grep ^PRETTY /etc/os-release | awk -F'"' '{print $2}'` # get the pretty name
  if [ ${#distro} = 0 ]; then
    echo "ERROR: did not find PRETTY_NAME in /etc/os-release" 
    exit 1
  fi
  echo "distro = $distro"
  pyVer=`python3 -V | awk '{print $2}' | awk -F. '{print $1 "." $2}'`
  commonPackages="bind9-dnsutils cifs-utils curl jq locate lsof mpc mpd net-tools pandoc pipewire pipewire-audio-client-libraries python3 python3-pip python3-rpi.gpio python3-venv python${pyVer}-venv raspi-config wireplumber" 

  echo "Installing co-req packages ..."
  for nextPkg in $commonPackages; do  
    runCmd sudo apt-get --quiet install -y $nextPkg
  done
  
  if [ ! -f /etc/vim/vimrc.orig ]; then    # never copied original
    runCmd sudo cp /etc/vim/vimrc /etc/vim/vimrc.orig
  fi    
  echo "Copying vimrc ..." 
  runCmd sudo cp $HOME/ovos-tools/vimrc /etc/vim
  echo
  
  echo "Adding groups to user pi ..." 
  runCmd sudo usermod -a -G audio,video,dialout,kmem pi
  echo "Adding groups to user mpd ..." 
  runCmd sudo usermod -a -G pi mpd
  echo "Adding groups spi, i2c and gpio to /etc/groump ..." 
  sudo groupadd -g 993 spi
  sudo groupadd -g 994 i2c
  sudo groupadd -g 993 gpio 
  echo
  
  # copy a .bash_profile specific to Neon, Minimy or OVOS 
  echo "Copying .bash_profile ..." 
  if [ "$flavor" = "minimy" ]; then     
    runCmd cp $HOME/ovos-tools/minimy_profile $HOME/.bash_profile
  elif [ "$flavor" = "neon" ]; then     
    runCmd cp $HOME/ovos-tools/neon_profile $HOME/.bash_profile
  elif [ "$flavor" = "ovos" ]; then     
    runCmd cp $HOME/ovos-tools/ovos_profile $HOME/.bash_profile
  fi
  
  # turn default and vc4 audio off, don't disable monitor overscan
  cd /boot/firmware 
  if [ ! -f config.txt.orig ]; then
    echo "Customizing boot parameters ..." 
    runCmd sudo cp config.txt config.txt.orig
    sudo sed -i -e 's/dtparam=audio=on/dtparam=audio=off\ndtparam=spi=off/g' \
                -e 's/^disable_overscan/# disable_overscan/g' \
                -e 's/^dtoverlay=vc4-kms-v3/# dtoverlay=vc4-kms-v3/g' config.txt
    local piModel=`cat /sys/firmware/devicetree/base/model | awk '{print $3}'`
    if [ "$piModel" = 5 ]; then            # 3 lines to get HiFiBerry running on a RasPi 5
      echo "dtoverlay=vc4-kms-v3d,noaudio" | sudo tee -a config.txt
      echo "dtoverlay=hifiberry-dacplus,slave" | sudo tee -a config.txt
      echo "force_eeprom_read=0" | sudo tee -a config.txt
    else                                   # assume RasPi 4
      echo "dtoverlay=hifiberry-dacplus-pro" | sudo tee -a config.txt # add hifiberry driver
    fi
  fi  
  
  # vim - traditional defaults, mouse works
  echo "Removing annoying autoindent from vim ..." 
  if [ ! -d $HOME/.vim ]; then
    runCmd mkdir $HOME/.vim 
  fi  
  cd $HOME/.vim
  echo "set noautoindent" >> vimrc
  echo "set nocindent" >> vimrc
  echo "set nosmartindent" >> vimrc
  # echo "set indentexpr=" >> vimrc
  
  # rsyslog can send a flood of kernel messages
  if [ -f /etc/rsyslog.conf -a ! -f /etc/rsyslog.conf.orig ]; then 
    echo "preventing rsyslogd from making log message storms ..." 
    runCmd sudo cp /etc/rsyslog.conf /etc/rsyslog.conf.orig
    sudo sed -i 's/^module(load="imklog"/# module(load="imklog"/g' /etc/rsyslog.conf
  fi
  
  # to lengthen the life of the memory device, write logs to a tmpfs 
  #if [ ! -f /etc/systemd/system/var-log.mount ]; then
  #  echo "Copying var-log.mount ..." 
  #  runCmd sudo cp ~/ovos-tools/var-log.mount /etc/systemd/system
  #fi
  
  # configure mpd
  if [ -f /etc/mpd.conf -a ! -f /etc/mpd.conf.orig ]; then # no backup has been made
    echo "Making backup of /etc/mpd.conf" 
    runCmd sudo cp /etc/mpd.conf /etc/mpd.conf.orig 
  fi
  if [ ! -d /var/log/mpd ]; then           # no mpd log dir
    sudo mkdir /var/log/mpd     
    sudo chown $USER /var/log/mpd
    sudo touch /var/log/mpd/mpd.log 
  fi
  echo "Copying sample mpd.conf file to /etc" 
  runCmd sudo cp ~/ovos-tools/mpd.conf /etc # copy sample 
  echo "Changing permissons of /etc/mpd.conf" 
  runCmd sudo chmod 644 /etc/mpd.conf  
  echo "Setting mpd to start at boot time" 
  runCmd sudo systemctl enable mpd         # start mpd at boot
  echo "Setting pipewire and pipewire-pulse to start at boot time..."
  runCmd systemctl --user enable pipewire pipewire-pulse
  echo "Disabling bluetooth ..."
  runCmd sudo systemctl disable bluetooth.service

  # configure USB hot plug to mount USB drive over /mnt/usb
  runCmd sudo cp ~/ovos-tools/99-mount-usb.rules /etc/udev/rules.d
  runCmd sudo cp ~/ovos-tools/usb-mount@.service /etc/systemd/system
  runCmd sudo cp ~/ovos-tools/usb-mount.sh /root 

  # configure the gateway to be the DNS resolver
  # DNSstmt=`grep ^DNS /etc/systemd/resolved.conf`
  # if [ ${#DNSstmt} = 0 ]; then             # DNS resolver not found
  #   gw=`ip route | head -1 | awk '{print $3}'` # get the gatway
  #   numDots=`echo $gw | awk -F'.' '{print NF}'` # check that it is dotted decimal
  #   if [ "$numDots" != 4 ]; then           # error
  #     echo "ERROR: $gw does not appear to be an IPv4 address"
  #     exit 1
  #   fi  
  #   echo "Setting $gw to DNS resolver..."
  #   echo "DNS=$gw" | sudo tee -a /etc/systemd/resolved.conf
  #   rc=$?
  #   if [ "$rc" != 0 ]; then
  #     echo "ERROR: echo DNS=$gw | sudo tee -a /etc/systemd/resolved.conf returned $rc"	  
  #   fi  
  #   runCmd sudo systemctl restart systemd-resolved
  # else
  #   echo "Found: $DNSstmt in /etc/systemd/resolved.conf"
  # fi
 }                                         # installCoreqs()

# main()
flavor="minimy"                            # minimy, neon or ovos
timeStamp=`date +"%y-%m-%d-%H-%M-%S"`   
outFile="$HOME/$timeStamp-install1.out"    # output file
parseArgs $@
checkOvosTools                             # verify ovos-tools is installed
echo "Running install1 on $timeStamp to configure $flavor ..." > $outFile # create a new log file
installCoreqs | tee -a $outFile            # do the work
let min=$SECONDS/60
let sec=$SECONDS%60
if [ $sec -lt 10 ]; then                   # add a leading 0
  sec="0$sec"
fi
echo "Successfully installed co-reqs for $flavor in $min:$sec" | tee -a $outFile
echo "Log file: $outFile"

