#!/bin/bash
#
# mpcupdate - run "mpc update" so mpd has the latest audio and log to a temp file
#
timeStamp=`date +"%y-%m-%d-%H:%M:%S"`
mpc update
echo "$timeStamp : mpcupdate - 'mpc update' return code: $?" | tee -a /tmp/mpcupdate
