#!/bin/bash
# mvmusic - move songs queued and playing on mpc/mpd to a remote Linux 
tgtBox="$1"
if [ ${#tgtBox} = 0 ]; then
  echo "ERROR: no target host specified"
  echo "Usage: mvmusic <target-host>"
  exit 1
fi
files=$(mpc -f %file% playlist)            # get songs file paths from mpc
if [ ${#files} = 0 ]; then
  echo "Say message: there are no songs playing nor paused"
  exit 2
fi
currentPos=$(mpc -f "%position%" current)  # get current song position, calculate elapsed time
state=$(mpc | awk '/^\[/ {gsub(/[\[\]]/, "", $1); print $1}')
elapTime=$(mpc | awk '/^\[/ {print $3}' | awk -F'/' '{print $1}')
elapSecs=$(echo "$elapTime" | awk -F: '{if(NF==2) print $1*60+$2; else if(NF==3) print $1*3600+$2*60+$3; else print 0}')
seekTime=$(( elapSecs - 10 ))
if [ "$seekTime" -lt 0 ]; then
  seekTime=0
fi
seekTime=$(printf "%02d:%02d:%02d" $((seekTime/3600)) $((seekTime%3600/60)) $((seekTime%60)))
echo "state: $state elapSecs: $elapSecs seekTime: $seekTime"
mpc stop                                   # stop music on local box

# stop music on target, add files and start
ssh -T "$tgtBox" << EOF
  mpc stop
  mpc clear
  echo "$files" | while read -r line; do mpc add "\$line"; done
  mpc play $currentPos
  sleep 2
  if [ "$seekTime" != 0 ]; then mpc seek $seekTime; fi
EOF

