#!/bin/bash
#
# neonver - get the Neon version from neon-core/version.py
#
baseDir="$HOME/venv/lib/python3.10/site-packages/neon_core"
if [ ! -d $baseDir ]; then
  echo "ERROR: directory $baseDir not found - is Neon installed?"
  exit 1
fi
cd $baseDir
if [ ! -f version.py ]; then               # version file not found
  echo "Unknown"
  exit 2
fi
neonVer=`grep "__version__" $baseDir/version.py | awk -F'"' '{print $2}'`
if [ ${#neonVer} = 0 ]; then 
  echo "Unknown"
  exit 3
else
  echo $neonVer
fi

# version.py
# ...
# __version__ = "23.12.28"
