#!/bin/bash
#
# sortlogs - merge and sort all log files 
#
tmpFile=`mktemp`                           # make a temp file
cd $HOME/minimy/logs
for i in *.log; do                         # copy all log files
  cat $i >> $tmpFile
done
outFile="/tmp/logs-`date +\"%F-%T\"`"
sort $tmpFile > $outFile                   # sort by timestamp
echo "sorted logs saved to: $outFile"
