#!/bin/bash
#
# sortlogs - merge and sort all log files 
#
tmpFile=`mktemp`                           # make a temp file
cd $HOME/minimy/logs
for i in *.log; do                         # copy all log files
  cat $i >> $tmpFile
done
timeStamp=`date +"%y-%m-%d-%H-%M-%S"`
outFile="$HOME/$timeStamp-minimy.logs"
sort $tmpFile > $outFile                   # sort by timestamp
echo "sorted logs saved to: $outFile"
